#ifndef INPUTPARAMETERS_H
#define INPUTPARAMETERS_H

using namespace std;

// The input parameter sequence

#if defined SQUAREPHONONS || defined TRIANGULARPHONONS || defined CUBICPHONONS || defined FCCPHONONS || defined BCCPHONONS 
const int NPARAMS = 32;
enum params{LINEID,J1X,J1Y,J1Z,J2X,J2Y,J2Z,J3X,J3Y,J3Z,g1X,g1Y,g1Z,g2X,g2Y,g2Z,ALPHA1,ALPHA2,NX,NY,NZ,DA,MU,EPSILONNULL,DELTASTART,DELTASLUTT,NDELTAS,DELTALOGSCALE,MAXITER,TOLERANCE,NBINS,EQFLAG};

#elif defined SQUARELAYEREDPHONONS || defined HEXAGONALLAYEREDPHONONS
const int NPARAMS = 33;
enum params{LINEID,J1X,J1Y,J1Z,J2X,J2Y,J2Z,J3X,J3Y,J3Z,g1X,g1Y,g1Z,g2X,g2Y,g2Z,ALPHA1,ALPHA2,ALPHAZ,NX,NY,NZ,DA,MU,EPSILONNULL,DELTASTART,DELTASLUTT,NDELTAS,DELTALOGSCALE,MAXITER,TOLERANCE,NBINS,EQFLAG};

#elif defined CrI3 || defined SQUARENOPHONONS || defined SQUAREXY
const int NPARAMS = 37;
enum params{LINEID,J1X,J1Y,J1Z,J2X,J2Y,J2Z,K1X,K1Y,K1Z,USEPHI,A,PHIOVERPI,AX,AY,AZ,DM1X,DM1Y,DM1Z,USEDMRPZ,DM1BR,DM1BP,DM1BZ,NX,NY,NZ,DA,MU,EPSILONNULL,DELTASTART,DELTASLUTT,NDELTAS,DELTALOGSCALE,MAXITER,TOLERANCE,NBINS,EQFLAG};

#endif

















#endif // INPUTPARAMETERS_H
