include Makefile.local


PPSOURCES =  bondpp.C bondpp.h matrixroutines.h overload.h bravaislattices.h vecmat.h modeldef.h couplings.h rules.h phonons.h inputparameters.h symmetryroutines.h observables.h makefile Makefile.local globalheader.h RunParameter.h rnddef.h


SQUARESOURCES      =  $(PPSOURCES) 
TRIANGULARSOURCES  =  $(PPSOURCES) triangularrules.h
HONEYCOMBSOURCES   =  $(PPSOURCES) honeycombrules.h
KAGOMESOURCES      =  $(PPSOURCES) kagomerules.h

SIMPLECUBICSOURCES =  $(PPSOURCES) simplecubicrules.h
DIAMONDSOURCES     =  $(PPSOURCES) diamondrules.h
PYROCHLORESOURCES  =  $(PPSOURCES) pyrochlorerules.h

all : planar 3d

planar : square.exec triangular.exec kagome.exec honeycomb.exec 

3d: simplecubic.exec diamond.exec pyrochlore.exec

sq : square.exec squaresymmrot.exec squaresymminv.exec



%.run  : %.exec
	./$<

%.exec : %.o 
	$(CCC) $(LINKOPTS) -o $@ $^ $(LIBDIR) $(LIBS)
	mv $*.exec $(BINDIR)/$*.`git describe`$(EXTENSION)



#square.o  : $(SQUARESOURCES)
#	$(CCC) $(CCFLAGS) -DSIMPLECUBICBRAVAISLATTICE -DNSUBLATTICES=1 -DSQUARELATTICE  -D#QSPACEDIRECTLATTICE -DNSPINCOMPONENTS=3 -DMAKEHERMITIAN -DFFTS_INPLACE -c -o $@ $<

#square.o  : $(SQUARESOURCES)
#	$(CCC) $(CCFLAGS) -DSIMPLECUBICBRAVAISLATTICE -DNSUBLATTICES=1 -DSQUAREPHONONS -DSQUARELATTICE  -DQSPACEDIRECTLATTICE -DPHONONS -DXYDISPLACEMENTS -DRANDOMINITIALIZATION -DFORCEINVERSIONSYMMETRY  -DFFTS_INPLACE -c -o $@ $<

squareHeisenberg.o  : $(SQUARESOURCES)
	$(CCC) $(CCFLAGS) -DSIMPLECUBICBRAVAISLATTICE -DNSUBLATTICES=1 -DSQUAREPHONONS -DSQUARELATTICE  -DQSPACEDIRECTLATTICE -DPHONONS -DXYDISPLACEMENTS -DRANDOMINITIALIZATION -DFORCEINVERSIONSYMMETRY -DFAKEHEISENBERG -DCPOSITIVE -DFFTS_INPLACE -c -o $@ $<

squareHeisenbergnophonons.o  : $(SQUARESOURCES)
	$(CCC) $(CCFLAGS) -DSIMPLECUBICBRAVAISLATTICE -DNSUBLATTICES=1 -DSQUAREPHONONS -DSQUARELATTICE  -DQSPACEDIRECTLATTICE -DPHONONS -DXYDISPLACEMENTS -DRANDOMINITIALIZATION -DFORCEINVERSIONSYMMETRY -DFAKEHEISENBERG -DCPOSITIVE -DFFTS_INPLACE -DOMITPHONONCONT -DOMITELASTICCONT -c -o $@ $<

squarelayeredHeisenberg.o  : $(SQUARESOURCES)
	$(CCC) $(CCFLAGS) -DSIMPLECUBICBRAVAISLATTICE -DNSUBLATTICES=1 -DSQUARELAYEREDPHONONS -DSQUARELATTICE  -DQSPACEDIRECTLATTICE -DPHONONS -DXYZDISPLACEMENTS -DRANDOMINITIALIZATION -DFORCEINVERSIONSYMMETRY -DFAKEHEISENBERG -DCPOSITIVE -DFFTS_INPLACE -c -o $@ $<

cubicHeisenberg.o  : $(SQUARESOURCES)
	$(CCC) $(CCFLAGS) -DSIMPLECUBICBRAVAISLATTICE -DNSUBLATTICES=1 -DCUBICPHONONS -DCUBICLATTICE -DQSPACEDIRECTLATTICE -DPHONONS -DXYZDISPLACEMENTS -DRANDOMINITIALIZATION -DFORCEINVERSIONSYMMETRY  -DFAKEHEISENBERG -DCPOSITIVE -DFFTS_INPLACE -c -o $@ $<

cubicHeisenbergnoselfenergy.o  : $(SQUARESOURCES)
	$(CCC) $(CCFLAGS) -DSIMPLECUBICBRAVAISLATTICE -DNSUBLATTICES=1 -DCUBICPHONONS -DCUBICLATTICE -DQSPACEDIRECTLATTICE -DPHONONS -DXYZDISPLACEMENTS -DRANDOMINITIALIZATION -DFORCEINVERSIONSYMMETRY -DNOSELFENERGY -DFAKEHEISENBERG -DCPOSITIVE -DFFTS_INPLACE -c -o $@ $<

cubicHeisenbergelasticonly.o  : $(SQUARESOURCES)
	$(CCC) $(CCFLAGS) -DSIMPLECUBICBRAVAISLATTICE -DNSUBLATTICES=1 -DCUBICPHONONS -DCUBICLATTICE -DQSPACEDIRECTLATTICE -DPHONONS -DELASTICONLY -DXYZDISPLACEMENTS -DRANDOMINITIALIZATION -DFORCEINVERSIONSYMMETRY -DFAKEHEISENBERG -DCPOSITIVE -DFFTS_INPLACE -c -o $@ $<

cubicHeisenbergnophonons.o  : $(SQUARESOURCES)
	$(CCC) $(CCFLAGS) -DSIMPLECUBICBRAVAISLATTICE -DNSUBLATTICES=1 -DCUBICLATTICE -DQSPACEDIRECTLATTICE -DRANDOMINITIALIZATION -DFORCEINVERSIONSYMMETRY  -DFAKEHEISENBERG -DCPOSITIVE -DFFTS_INPLACE -c -o $@ $<

triangularHeisenberg.o  : $(SQUARESOURCES)
	$(CCC) $(CCFLAGS) -DHEXAGONALBRAVAISLATTICE -DNSUBLATTICES=1 -DTRIANGULARPHONONS -DHEXAGONALLATTICE  -DQSPACEDIRECTLATTICE -DPHONONS -DXYDISPLACEMENTS -DRANDOMINITIALIZATION -DFORCEINVERSIONSYMMETRY -DFAKEHEISENBERG -DCPOSITIVE -DFFTS_INPLACE -c -o $@ $<

triangularlayeredHeisenberg.o  : $(SQUARESOURCES)
	$(CCC) $(CCFLAGS) -DHEXAGONALBRAVAISLATTICE -DNSUBLATTICES=1 -DTRIANGULARLAYEREDPHONONS -DHEXAGONALLATTICE -DQSPACEDIRECTLATTICE -DPHONONS -DXYZDISPLACEMENTS -DRANDOMINITIALIZATION -DFORCEINVERSIONSYMMETRY  -DFAKEHEISENBERG -DCPOSITIVE -DFFTS_INPLACE -c -o $@ $<

fccHeisenberg.o  : $(SQUARESOURCES)
	$(CCC) $(CCFLAGS) -DFCCBRAVAISLATTICE -DNSUBLATTICES=1 -DFCCPHONONS -DFCCLATTICE -DQSPACEDIRECTLATTICE -DPHONONS -DXYZDISPLACEMENTS -DRANDOMINITIALIZATION -DFORCEINVERSIONSYMMETRY  -DFAKEHEISENBERG -DCPOSITIVE -DFFTS_INPLACE -c -o $@ $<

bccHeisenberg.o  : $(SQUARESOURCES)
	$(CCC) $(CCFLAGS) -DBCCBRAVAISLATTICE -DNSUBLATTICES=1 -DBCCPHONONS -DBCCLATTICE -DQSPACEDIRECTLATTICE -DPHONONS -DXYZDISPLACEMENTS -DRANDOMINITIALIZATION -DFORCEINVERSIONSYMMETRY  -DFAKEHEISENBERG -DCPOSITIVE -DFFTS_INPLACE -c -o $@ $<



CrI3nooffd.o  : $(SQUARESOURCES)
	$(CCC) $(CCFLAGS) -DHEXAGONALBRAVAISLATTICE -DNSUBLATTICES=2 -DCrI3 -DHEXAGONALLATTICE -DQSPACEDIRECTLATTICE -DRANDOMINITIALIZATION -DFORCEINVERSIONSYMMETRY -DFFTS_INPLACE -DFFTS_INPLACE -DNORANDOMSPINOFFDIAGONALS -c -o $@ $<

CrI3ssym.o  : $(SQUARESOURCES)
	$(CCC) $(CCFLAGS) -DHEXAGONALBRAVAISLATTICE -DNSUBLATTICES=2 -DCrI3 -DHEXAGONALLATTICE -DQSPACEDIRECTLATTICE -DRANDOMINITIALIZATION -DFORCEINVERSIONSYMMETRY -DFFTS_INPLACE -DFFTS_INPLACE -DNORANDOMSPINOFFDIAGONALS -DEQUALRANDOMSPINDIAGONALS -c -o $@ $<


CrI3.o  : $(SQUARESOURCES)
	$(CCC) $(CCFLAGS) -DHEXAGONALBRAVAISLATTICE -DNSUBLATTICES=2 -DCrI3 -DHEXAGONALLATTICE -DQSPACEDIRECTLATTICE -DRANDOMINITIALIZATION -DFORCEINVERSIONSYMMETRY -DFFTS_INPLACE -DFFTS_INPLACE -c -o $@ $<


CrI3iso.o  : $(SQUARESOURCES)
	$(CCC) $(CCFLAGS) -DHEXAGONALBRAVAISLATTICE -DNSUBLATTICES=2 -DCrI3 -DHEXAGONALLATTICE -DQSPACEDIRECTLATTICE -DRANDOMINITIALIZATION -DFORCEINVERSIONSYMMETRY -DFFTS_INPLACE -DFFTS_INPLACE -DSPINISOTROPIC -c -o $@ $<

squareiso.o  : $(SQUARESOURCES)
	$(CCC) $(CCFLAGS) -DSIMPLECUBICBRAVAISLATTICE -DNSUBLATTICES=1 -DSQUARENOPHONONS -DSQUARELATTICE -DQSPACEDIRECTLATTICE -DRANDOMINITIALIZATION -DFORCEINVERSIONSYMMETRY -DFFTS_INPLACE -DFFTS_INPLACE -DSPINISOTROPIC -c -o $@ $<

square.o  : $(SQUARESOURCES)
	$(CCC) $(CCFLAGS) -DSIMPLECUBICBRAVAISLATTICE -DNSUBLATTICES=1 -DSQUARENOPHONONS -DSQUARELATTICE -DQSPACEDIRECTLATTICE -DRANDOMINITIALIZATION -DFORCEINVERSIONSYMMETRY -DFFTS_INPLACE -DFFTS_INPLACE -c -o $@ $<

squarenooffd.o  : $(SQUARESOURCES)
	$(CCC) $(CCFLAGS) -DSIMPLECUBICBRAVAISLATTICE -DNSUBLATTICES=1 -DSQUARENOPHONONS -DSQUARELATTICE -DQSPACEDIRECTLATTICE -DRANDOMINITIALIZATION -DFORCEINVERSIONSYMMETRY -DFFTS_INPLACE -DFFTS_INPLACE -DNORANDOMSPINOFFDIAGONALS -c -o $@ $<

squareXY.o  : $(SQUARESOURCES)
	$(CCC) $(CCFLAGS) -DSIMPLECUBICBRAVAISLATTICE -DNSUBLATTICES=1 -DSQUAREXY -DSQUARELATTICE -DQSPACEDIRECTLATTICE -DRANDOMINITIALIZATION -DFORCEINVERSIONSYMMETRY -DFFTS_INPLACE -DFFTS_INPLACE -c -o $@ $<

squareXYiso.o  : $(SQUARESOURCES)
	$(CCC) $(CCFLAGS) -DSIMPLECUBICBRAVAISLATTICE -DNSUBLATTICES=1 -DSQUAREXY -DSQUARELATTICE -DQSPACEDIRECTLATTICE -DRANDOMINITIALIZATION -DFORCEINVERSIONSYMMETRY -DFFTS_INPLACE -DFFTS_INPLACE -DSPINISOTROPIC -c -o $@ $<

squareXYnooffd.o  : $(SQUARESOURCES)
	$(CCC) $(CCFLAGS) -DSIMPLECUBICBRAVAISLATTICE -DNSUBLATTICES=1 -DSQUAREXY -DSQUARELATTICE -DQSPACEDIRECTLATTICE -DRANDOMINITIALIZATION -DFORCEINVERSIONSYMMETRY -DFFTS_INPLACE -DFFTS_INPLACE -DNORANDOMSPINOFFDIAGONALS -c -o $@ $<


spotless:       
	make clean
	rm -f *.ps

clean   :
	rm -f *.dvi
	rm -f *.aux
	rm -f *.log
	rm -f *~
	rm -f core
	rm -f *.o	
	rm -f *.exec
	rm -f *.d

