DATADIR = $(HOME)
HOMEDIR = $(HOME)
INCDIR = -I$(DATADIR)/include -I$(HOMEDIR)/include -I/usr/include -I/usr/local/include 
LIBDIR = -L$(DATADIR)/lib     -L$(HOMEDIR)/lib     -L/usr/lib -L/usr/local/lib 
LIBS   = -lfftw3 -lm -lstdc++ 
BINDIR = $(DATADIR)/bin
EXTENSION = _osx.x



# C++ compiler
CCC= g++
CCOPTS= -O -g -Wall
LINKOPTS =  -O3 -Wall
CCFLAGS = $(CCOPTS) $(INCDIR) 






